export const PLANES = [
      {
        nombre: "Básico",
        precio: "12 meses a $99 cada uno",
        detalles: [
          "Configuración completa de tu empresa o marca",
          "Segmentación básica del público objetivo",
          "Generación de publicaciones con tono, idioma y extensión definidos",
          "Hasta 45 publicaciones mensuales",
          "Nivel de IA: Básica",
          "Suscripción anual incluida: 1ª gratuita",
          "Renovación después del primer año: $300",
        ],
        namekey:'Plan Básico Mensual',

        extras: [],
      },
      {
        nombre: "Pro",
        precio: "12 meses a $349 cada uno",
        detalles: [
          "Configuración completa de tu empresa o marca",
          "Segmentación básica del público objetivo",
          "Generación de publicaciones con tono, idioma y extensión definidos",
          "Hasta 100 publicaciones mensuales",
          "Inspiración con textos o autores famosos",
          "Comunicación  ultra personalizada",
          "Nivel de IA: Básica y Potente",
          "Suscripción anual: $500 / año",
        //   "Pago anticipado: $3,270.40 (ahorra 20%)",          
          // "Renovación despues del año: $300",
        ],
        extras: [],
        namekey:'Plan Pro Mensual',
      },
      {
        nombre: "Premium (A medida)",
        precio: "Cotización",
        detalles: [
          "Configuración completa de tu empresa o marca",
          "Segmentación básica del público objetivo",
          "Generación de publicaciones con tono, idioma y extensión definidos",
          "Publicaciones: Según contrato",
          "Inspiración con textos o autores famosos",
          "Segmentación ultra personalizada",
          "Nivel de IA: Básica y Potente",
          "Suscripción anual: Cotización",
          "Pago anticipado: Cotización",
          "Renovación automática: 1 año gratis",
          "Integración con sistemas internos",
          "Workflows personalizados",
          "Soporte y capacitación avanzada",
        ],
        extras: [],
        namekey:'',
      },
    ]