import type { Metadata, Viewport } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "@/app/globals.css";
import { Toaster } from "sonner";
import { AdminProtected } from "@/components/protected/admin.protected";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "GAC - Generador de Contenido",
  description: "Generated by IActiva",  
};


 

export const viewport: Viewport = {
  width: 'device-width',
  initialScale: 1,
};

// // export default function RootLayout({
// //   children,
// // }: Readonly<{
// //   children: React.ReactNode;
// // }>) {
// //   return (

// //     <AdminProtected>
// //       <html lang="en">

// //       <body
// //         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
// //       >
// //        <nav className="bg-white shadow-md">
// //           <div className="container mx-auto px-4 py-3 flex items-center justify-between">
// //             {/* Logo principal (responsivo) */}
// //             <Image
// //               className="w-1/3 sm:w-1/4 md:w-[120px]"
// //               src="/logos/logo.webp"
// //               alt="Logo"
// //               width={200}
// //               height={200}
// //             />

// //             {/* Links de navegación */}
// //             <ul className="hidden md:flex space-x-6 text-sm md:text-base font-medium">
// //               <li>
// //                 <Link href="/" className="hover:text-blue-600 transition">GAC</Link>
// //                 {/* <a href="/" className="hover:text-blue-600 transition">GAC</a> */}
// //               </li>
// //               <li>
// //                 <Link href="/admin/gestion" className="hover:text-blue-600 transition">Gestión de usuarios</Link>
// //                 {/* <a href="/about" className="hover:text-blue-600 transition">Gestión de usuarios</a> */}
// //               </li>
// //             </ul>
// //           </div>
// //         </nav>


// //           <Toaster position="top-center"  richColors  toastOptions={
// //           {
// //             style: {              
// //               width:"max-content",
// //               left: "50%",
// //               transform: "translateX(-50%)",              
// //             }
// //           }
// //         }/>
// //           {children}

// //       </body>

// //     </html>
// //   </AdminProtected>
    
// //   );
// // }


// export default function RootLayout({
//   children,
// }: {
//   children: React.ReactNode
// }) {
//   return (
//     <html lang="en">
//       <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
//         <AdminProtected>
//           <nav className="bg-white shadow-md">
//             <div className="container mx-auto px-4 py-3 flex items-center justify-between">
//               {/* Logo principal */}
//               <Image
//                 className="w-1/3 sm:w-1/4 md:w-[120px]"
//                 src="/logos/logo.webp"
//                 alt="Logo"
//                 width={200}
//                 height={200}
//               />
//               <ul className="hidden md:flex space-x-6 text-sm md:text-base font-medium">
//                 <li>
//                   <Link href="/" className="hover:text-blue-600 transition">GAC</Link>
//                 </li>
//                 <li>
//                   <Link href="/admin/gestion" className="hover:text-blue-600 transition">Gestión de usuarios</Link>
//                 </li>
//               </ul>
//             </div>
//           </nav>

//           <Toaster
//             position="top-center"
//             richColors
//             toastOptions={{
//               style: {
//                 width: "max-content",
//                 left: "50%",
//                 transform: "translateX(-50%)",
//               },
//             }}
//           />

//           {children}
//         </AdminProtected>
//       </body>
//     </html>
//   );
// }


import { Navbar } from "./navbar";

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        {/* <AdminProtected> */}
          <Navbar />
          <Toaster
            position="top-center"
            richColors
            toastOptions={{
              style: {
                width: "max-content",
                left: "50%",
                transform: "translateX(-50%)",
              },
            }}
          />
          {children}
        {/* </AdminProtected> */}
      </body>
    </html>
  );
}
