import { Navbar } from "./navbar";

import type { Metadata, Viewport } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "@/app/globals.css";
import { Toaster } from "sonner";
import { AdminProtected } from "@/components/protected/admin.protected";
import { Protected } from "@/components/protected/protected";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "GAC - Generador de Contenido",
  description: "Generated by IActiva",  
};


 

export const viewport: Viewport = {
  width: 'device-width',
  initialScale: 1,
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <Protected> 
          <Navbar />
          <Toaster
            position="top-center"
            richColors
            toastOptions={{
              style: {
                width: "max-content",
                left: "50%",
                transform: "translateX(-50%)",
              },
            }}
          />
          {children}
        </Protected>
      </body>
    </html>
  );
}