export const SECTORES =[
    'Contabilidad',
    'Aerolíneas/aviación',
    'Resolución de conflictos alternativa',
    'Medicina alternativa',
    'Animación',
    'Ropa y moda',
    'Arquitectura y planificación',
    'Artes y oficios',
    'Automoción',
    'Aviación e industria aeroespacial',
    'Banca',
    'Biotecnología',
    'Medios de difusión',
    'Materiales de construcción',
    'Artículos y equipamiento de oficina',
    'Mercados de capitales',
    'Productos químicos',
    'Organización cívica y social',
    'Ingeniería civil',
    'Bienes inmuebles comerciales',
    'Seguridad informática y de red',
    'Juegos de ordenador',
    'Hardware de ordenador',
    'Redes informáticas',
    'Software de ordenador',
    'Internet',
    'Construcción',
    'Electrónica de consumo',
    'Bienes de consumo',
    'Servicio al consumidor',
    'Productos cosméticos',
    'Productos lácteos',
    'Defensa y espacio',
    'Diseño',
    'Administración de educación',
    'E-Learning',
    'Manufactura eléctrica/electrónica',
    'Entretenimiento',
    'Servicios ambientales'    
]